# Generated by Django 5.0.1 on 2024-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_fullname_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session',
            field=models.CharField(choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19')], default='00-00', max_length=50),
        ),
    ]
