# Generated by Django 5.0.1 on 2024-02-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_departmental_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departmental_batch',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], default='NULL', max_length=50),
        ),
    ]
