# Generated by Django 5.0.1 on 2024-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_departmental_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
