# Generated by Django 5.0.1 on 2024-02-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
