# Generated by Django 5.0.1 on 2024-02-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_profile_departmental_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('batch_ambassador', 'Batch Ambassador'), ('departmental_ambassador', 'Departmental Ambassador'), ('university_ambassador', 'University Ambassador'), ('admin', 'Admin')], max_length=100, null=True),
        ),
    ]
