# Generated by Django 5.0.1 on 2024-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_profile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')], null=True),
        ),
    ]
