# Generated by Django 4.2.3 on 2023-11-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_notemodel_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='session',
            field=models.CharField(choices=[('2024-2025', '2024-2025'), ('2023-2024', '2023-2024'), ('2022-2023', '2022-2023'), ('2021-2022', '2021-2022'), ('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019')], max_length=50),
        ),
    ]
