# Generated by Django 4.2.3 on 2023-11-15 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0004_course_syllabus_alter_notemodel_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ambassadors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
