# Generated by Django 4.2.3 on 2023-11-17 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0005_department_ambassadors'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('semester', models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')])),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=100)),
                ('book_file', models.FileField(upload_to='study/books/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.university')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
