# Generated by Django 4.2.3 on 2023-11-17 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0006_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('semester', models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')])),
                ('session', models.CharField(choices=[('2024-2025', '2024-2025'), ('2023-2024', '2023-2024'), ('2022-2023', '2022-2023'), ('2021-2022', '2021-2022'), ('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019')], max_length=50)),
                ('lecture_title', models.CharField(max_length=200)),
                ('lecture_author', models.CharField(max_length=100)),
                ('lecture_file', models.FileField(upload_to='study/lectures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.university')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
