# Generated by Django 4.2.3 on 2023-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_lecturemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturemodel',
            name='session',
            field=models.CharField(choices=[('2024-25', '2024-2025'), ('2023-24', '2023-2024'), ('2022-23', '2022-2023'), ('2021-22', '2021-2022'), ('2020-21', '2020-2021'), ('2019-20', '2019-2020'), ('2018-19', '2018-2019')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='session',
            field=models.CharField(choices=[('2024-25', '2024-2025'), ('2023-24', '2023-2024'), ('2022-23', '2022-2023'), ('2021-22', '2021-2022'), ('2020-21', '2020-2021'), ('2019-20', '2019-2020'), ('2018-19', '2018-2019')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.CharField(choices=[('2024-25', '2024-2025'), ('2023-24', '2023-2024'), ('2022-23', '2022-2023'), ('2021-22', '2021-2022'), ('2020-21', '2020-2021'), ('2019-20', '2019-2020'), ('2018-19', '2018-2019')], max_length=9),
        ),
    ]
