# Generated by Django 5.0.1 on 2024-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_alter_lecturemodel_session_alter_notemodel_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hour',
            field=models.PositiveIntegerField(default=100, max_length=3),
        ),
    ]
