# Generated by Django 5.0.1 on 2024-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_course_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturemodel',
            name='session',
            field=models.CharField(choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='session',
            field=models.CharField(choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_name',
            field=models.CharField(choices=[('1st Mid', '1st Mid'), ('2nd Mid', '2nd Mid'), ('3rd Mid', '3rd Mid'), ('Class Test', 'Class Test'), ('Lab Test', 'Lab Test'), ('Lab Final', 'Lab Final'), ('Final', 'Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.CharField(choices=[('24-25', '24-25'), ('23-24', '23-24'), ('22-23', '22-23'), ('21-22', '21-22'), ('20-21', '20-21'), ('19-20', '19-20'), ('18-19', '18-19')], max_length=9),
        ),
    ]
