# Generated by Django 5.0.1 on 2024-02-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_departmental_batch'),
        ('study', '0011_alter_course_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
