# Generated by Django 5.0.1 on 2024-02-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_alter_bookmodel_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='system',
            field=models.CharField(choices=[('year', 'Year'), ('semester', 'Semester')], default='semester', max_length=100),
        ),
    ]
