# Generated by Django 5.0.1 on 2024-02-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_alter_bookmodel_semester_alter_lecturemodel_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.faculty'),
        ),
    ]
