# Generated by Django 5.0.1 on 2024-02-09 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_teacher_department_teacher_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.teacher'),
        ),
    ]
