# Generated by Django 5.0.1 on 2024-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0020_alter_course_semester_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='semester',
            field=models.PositiveIntegerField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')]),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='year',
            field=models.PositiveIntegerField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')]),
        ),
        migrations.AlterField(
            model_name='lecturemodel',
            name='semester',
            field=models.PositiveIntegerField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')]),
        ),
        migrations.AlterField(
            model_name='lecturemodel',
            name='year',
            field=models.PositiveIntegerField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')]),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='semester',
            field=models.PositiveIntegerField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')]),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='year',
            field=models.PositiveIntegerField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')], max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], max_length=5),
        ),
    ]
