# Generated by Django 5.0.1 on 2024-02-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0023_alter_question_semester_alter_question_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='num_of_seat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
